version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '03:49'
    commit-message:
      prefix: 'build'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '03:49'
    commit-message:
      prefix: 'fix'
      prefix-development: 'build'
