name: pr-pipeline
on:
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:ci
      - name: Test
        run: npm run cover:ci
      - name: Build
        run: npm run build
